// Strongly-typed Design Tokens Matching tokens.css

export const TOKENS = {
  typography: {
    fontSans: 'var(--font-family-sans)',
    fontMono: 'var(--font-family-mono)',
    weights: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
    sizes: {
      display: 'var(--font-size-display)',
      h1: 'var(--font-size-h1)',
      h2: 'var(--font-size-h2)',
      h3: 'var(--font-size-h3)',
      h4: 'var(--font-size-h4)',
      bodyLg: 'var(--font-size-body-lg)',
      body: 'var(--font-size-body)',
      bodySm: 'var(--font-size-body-sm)',
      caption: 'var(--font-size-caption)',
    },
    lineHeights: {
      display: 'var(--line-height-display)',
      heading: 'var(--line-height-heading)',
      body: 'var(--line-height-body)',
      tight: 'var(--line-height-tight)',
    },
  },
  colors: {
    bg: 'var(--color-bg)',
    surface: 'var(--color-surface)',
    surfaceRaised: 'var(--color-surface-raised)',
    surfaceHover: 'var(--color-surface-hover)',
    surfaceActive: 'var(--color-surface-active)',
    text: 'var(--color-text)',
    textMuted: 'var(--color-text-muted)',
    textSubtle: 'var(--color-text-subtle)',
    border: 'var(--color-border)',
    borderSubtle: 'var(--color-border-subtle)',
    borderStrong: 'var(--color-border-strong)',
    primary: 'var(--color-primary)',
    primaryHover: 'var(--color-primary-hover)',
    accent: 'var(--color-accent)',
    accentHover: 'var(--color-accent-hover)',
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    danger: 'var(--color-danger)',
    info: 'var(--color-info)',
  },
  spacing: {
    1: 'var(--space-1)',
    2: 'var(--space-2)',
    3: 'var(--space-3)',
    4: 'var(--space-4)',
    5: 'var(--space-5)',
    6: 'var(--space-6)',
    8: 'var(--space-8)',
    10: 'var(--space-10)',
    12: 'var(--space-12)',
    16: 'var(--space-16)',
    20: 'var(--space-20)',
    24: 'var(--space-24)',
    30: 'var(--space-30)',
  },
  radii: {
    xs: 'var(--radius-xs)',
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    pill: 'var(--radius-pill)',
  },
  shadows: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    glowPrimary: 'var(--shadow-glow-primary)',
    glowAccent: 'var(--shadow-glow-accent)',
  },
  motion: {
    durationFast: 'var(--duration-fast)',
    durationNormal: 'var(--duration-normal)',
    durationModerate: 'var(--duration-moderate)',
    durationSlow: 'var(--duration-slow)',
    easeStandard: 'var(--ease-standard)',
    easeEmphasis: 'var(--ease-emphasis)',
    easeSpring: 'var(--ease-spring)',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1440px',
  },
} as const;

export type ThemeTokens = typeof TOKENS;
