import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route, Link } from 'react-router-dom';
function HomePage() {
    return (_jsxs("div", { style: { padding: '4rem 2rem', maxWidth: '1200px', margin: '0 auto' }, children: [_jsxs("header", { style: { marginBottom: '3rem' }, children: [_jsx("span", { style: { fontSize: '0.875rem', fontWeight: 600, color: 'var(--color-primary)', textTransform: 'uppercase', letterSpacing: '0.05em' }, children: "Public Website Foundation" }), _jsx("h1", { style: { fontSize: '3rem', fontWeight: 800, marginTop: '0.5rem', marginBottom: '1rem', lineHeight: 1.15 }, children: "NexaTalent" }), _jsx("p", { style: { fontSize: '1.25rem', color: 'var(--color-text-muted)', maxWidth: '640px' }, children: "A modern recruitment and talent solutions platform connecting businesses, recruiters, and candidates." })] }), _jsxs("section", { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1.5rem', marginTop: '2rem' }, children: [_jsxs("div", { style: { padding: '1.75rem', backgroundColor: 'var(--color-surface)', borderRadius: '12px', border: '1px solid var(--color-border)' }, children: [_jsx("h3", { style: { fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.5rem' }, children: "For Employers" }), _jsx("p", { style: { color: 'var(--color-text-muted)', fontSize: '0.95rem', marginBottom: '1rem' }, children: "Scale your team with verified specialist talent and real-time candidate pipeline visibility." }), _jsx("a", { href: "/employers", style: { color: 'var(--color-primary)', fontWeight: 600, fontSize: '0.875rem' }, children: "Explore Employer Solutions \u2192" })] }), _jsxs("div", { style: { padding: '1.75rem', backgroundColor: 'var(--color-surface)', borderRadius: '12px', border: '1px solid var(--color-border)' }, children: [_jsx("h3", { style: { fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.5rem' }, children: "For Candidates" }), _jsx("p", { style: { color: 'var(--color-text-muted)', fontSize: '0.95rem', marginBottom: '1rem' }, children: "Access curated career opportunities across high-growth engineering, product, and leadership roles." }), _jsx("a", { href: "/jobs", style: { color: 'var(--color-primary)', fontWeight: 600, fontSize: '0.875rem' }, children: "Browse Open Roles \u2192" })] })] })] }));
}
function NotFoundPage() {
    return (_jsxs("div", { style: { padding: '4rem 2rem', textAlign: 'center' }, children: [_jsx("h2", { style: { fontSize: '2rem', marginBottom: '1rem' }, children: "404 \u2014 Page Not Found" }), _jsx("p", { style: { color: 'var(--color-text-muted)', marginBottom: '1.5rem' }, children: "The page you requested does not exist." }), _jsx(Link, { to: "/", style: { color: 'var(--color-primary)', fontWeight: 600 }, children: "Return to Homepage" })] }));
}
export function AppRoutes() {
    return (_jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "*", element: _jsx(NotFoundPage, {}) })] }));
}
//# sourceMappingURL=index.js.map